In [9]:
import os
import pandas as pd
df = pd.read_csv('../data/filtered/final_data.csv')

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Air India,10682.0,0.163921,0.370221,0.0,0.0,0.0,0.0,1.0
GoAir,10682.0,0.018161,0.133541,0.0,0.0,0.0,0.0,1.0
IndiGo,10682.0,0.192192,0.394042,0.0,0.0,0.0,0.0,1.0
Jet Airways,10682.0,0.360326,0.480117,0.0,0.0,0.0,1.0,1.0
Jet Airways Business,10682.0,0.000562,0.023695,0.0,0.0,0.0,0.0,1.0
Multiple carriers,10682.0,0.111964,0.315337,0.0,0.0,0.0,0.0,1.0
Multiple carriers Premium economy,10682.0,0.001217,0.034866,0.0,0.0,0.0,0.0,1.0
SpiceJet,10682.0,0.076577,0.265932,0.0,0.0,0.0,0.0,1.0
Trujet,10682.0,0.000094,0.009676,0.0,0.0,0.0,0.0,1.0
Vistara,10682.0,0.044842,0.206966,0.0,0.0,0.0,0.0,1.0
Vistara Premium economy,10682.0,0.000281,0.016757,0.0,0.0,0.0,0.0,1.0
Source_Chennai,10682.0,0.035667,0.185468,0.0,0.0,0.0,0.0,1.0
Source_Delhi,10682.0,0.424640,0.494311,0.0,0.0,0.0,1.0,1.0
Source_Kolkata,10682.0,0.268770,0.443341,0.0,0.0,0.0,1.0,1.0
Source_Mumbai,10682.0,0.065250,0.246978,0.0,0.0,0.0,0.0,1.0
Destination_Cochin,10682.0,0.424640,0.494311,0.0,0.0,0.0,1.0,1.0
Destination_Delhi,10682.0,0.205673,0.404212,0.0,0.0,0.0,0.0,1.0
Destination_Hyderabad,10682.0,0.065250,0.246978,0.0,0.0,0.0,0.0,1.0
Destination_Kolkata,10682.0,0.035667,0.185468,0.0,0.0,0.0,0.0,1.0
Total_Stops,10682.0,0.824190,0.675229,0.0,0.0,1.0,1.0,4.0
Price,10682.0,9087.214567,4611.548810,1759.0,5277.0,8372.0,12373.0,79512.0
Day_of_Journey,10682.0,13.509081,8.479363,1.0,6.0,12.0,21.0,27.0
Month_of_Journey,10682.0,4.708575,1.164408,3.0,3.0,5.0,6.0,6.0
Dep_Hour,10682.0,12.491013,5.748820,0.0,8.0,11.0,18.0,23.0
Dep_Minute,10682.0,24.409287,18.767801,0.0,5.0,25.0,40.0,55.0
Arrival_Hour,10682.0,13.349186,6.859317,0.0,8.0,14.0,19.0,23.0
Arrival_Minute,10682.0,24.690601,16.506808,0.0,10.0,25.0,35.0,55.0
Duration_hours,10682.0,10.245366,8.494489,1.0,2.0,8.0,15.0,47.0
Duration_minutes,10682.0,28.326156,16.946530,0.0,15.0,30.0,45.0,55.0